=== LordMathis/namesny.com/src/utils/configSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "required": [
        "title",
        "name",
        "baseUrl"
    ],
    "additionalProperties": true,
    "properties": {
        "title": {
            "$id": "#/properties/title",
            "type": "string",
            "title": "The title schema",
            "description": "The title of the website"
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The name schema",
            "description": "Your name",
            "examples": [
                "John Doe"
            ]
        },
        "email": {
            "$id": "#/properties/email",
            "type": "string",
            "title": "The email schema",
            "description": "Your email",
            "default": "",
            "examples": [
                "john.doe@example.com"
            ]
        },
        "social": {
            "$id": "#/properties/social",
            "type": "object",
            "title": "The social schema",
            "description": "Links to your social accounts",
            "default": {},
            "examples": [
                {
                    "linkedin": "https://www.linkedin.com/in/johndoe/",
                    "codepen": "https://codepen.io/johndoe/",
                    "github": "https://github.com/johndoe"
                }
            ],
            "additionalProperties": true
        },
        "baseUrl": {
            "$id": "#/properties/baseUrl",
            "type": "string",
            "title": "The baseUrl schema",
            "description": "Base URL of your website",
            "examples": [
                "example.com"
            ]
        },
        "storage": {
            "$id": "#/properties/storage",
            "type": "string",
            "enum": ["mongo", "file"],
            "title": "The storage schema",
            "description": "The content storage configuration",
            "default": "file"
        },
        "mongourl": {
            "$id": "#/properties/mongourl",
            "type": "string",
            "title": "The mongourl schema",
            "description": "Sets MongoDb url if mongo is specified as a storage option.",
            "examples": [
                "mongodb://localhost:27017"
            ]
        },
        "contentPath": {
            "$id": "#/properties/contentPath",
            "type": "string",
            "title": "The contentPath schema",
            "description": "The path to your content.",
            "examples": [
                "./content"
            ]
        },
        "specialFiles": {
            "$id": "#/properties/specialFiles",
            "type": "array",
            "title": "The specialFiles schema",
            "description": "Files that are not normal blog posts.",
            "default": [],
            "examples": [
                [
                    "about.md",
                    "resume.md"
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/specialFiles/items",
                "anyOf": [
                    {
                        "$id": "#/properties/specialFiles/items/anyOf/0",
                        "type": "string",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": "",
                        "examples": [
                            "about.md",
                            "resume.md"
                        ]
                    }
                ]
            }
        }
    }
}

=== LordMathis/namesny.com/config/config.example.json
{
    "title": "John Doe - Portfolio",
    "name": "John Doe",
    "email": "john.doe@example.com",
    "social": {
      "github": "github_url",
      "twitter": "twitter_url",
      "linkedin": "linkedin_url"
    },
    "baseUrl": "example.com",
    "contentPath": "./content",
    "storage": "file",
    "specialFiles": [
      "about.md", "resume.md"
    ]
  }
